name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static-analysis:
    runs-on: ubuntu-20.04
    name: Static Analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Set up Terramate
        run: go install github.com/mineiros-io/terramate/cmd/terramate@v0.1.5

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
          terraform_wrapper: false

      - name: Check Formatting
        run: terraform fmt -recursive -check -no-color

      - name: Initialize Stacks
        run: terramate run -- terraform init

      - name: Validate Stacks
        run: terramate run -- terraform validate
